### ISSUE TITLE
JAR: NoClassDefFoundError

### ISSUE THREAD

**Issue by harmathy** [mediathekview/MediathekView#795]
Unter Linux baue ich den Code und rufe das JAR auf:

```sh
./mvnw clean install
java -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:+UseStringDeduplication -XX:MaxRAMPercentage=25 --add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED -DexternalUpdateCheck -jar ./target/MediathekView.jar
```

Fehler:

```
Error: Unable to initialize main class mediathek.Main
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/Layout
```

Nach einem `git bisect` tritt das Problem erstmal mit Commit 25934bc4257a8f3319a08158766b00e44ceb637c auf.

**Comment by MuenchenSued** [comment]
Versuch mal folgenden Aufruf:
`
java -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:+UseStringDeduplication -XX:MaxRAMPercentage=50.0
--enable-native-access=ALL-UNNAMED --add-modules jdk.incubator.vector --add-exports=java.desktop/sun.swing=ALL-UNNAMED 
--add-opens java.desktop/sun.awt.X11=ALL-UNNAMED -ea -cp "MediathekView.jar:dependency/*" mediathek.Main
`

**Comment by harmathy** [comment]
@styroll Ich habe einen Pull-Request #796 eröffnet, der das Problem behebt. Damit kann man das Jar-File wie bisher starten.

**Comment by dvzrv** [comment]
Hi! Ich package dieses Projekt fuer Arch Linux.
In Version 14.3.1 habe ich das selbe Problem wie hier beschrieben und bekomme die Applikation gar nicht mehr zu laufen.

Sind diese Aenderungen bereits released?

**Comment by dvzrv** [comment]
Auch nach Nutzung des Patches aus #796 bekomme ich folgendes in 14.3.1:

```bash
java -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:+UseStringDeduplication -XX:MaxRAMPercentage=25 --add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED --add-exports=java.desktop/sun.swing=ALL-UNNAMED --enable-native-access=ALL-UNNAMED --
add-modules jdk.incubator.vector -DexternalUpdateCheck -jar /usr/share/java/mediathekview/MediathekView.jar /home/user/.local/share/mediathekview
Picked up _JAVA_OPTIONS: -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
WARNING: Using incubator modules: jdk.incubator.vector
Error: Unable to initialize main class mediathek.Main
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/Layout
```
